services:
  web:
    build: .
    container_name: rieger-web
    restart: always
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rieger.rule=Host(`rieger-systems.eu`)'
      - 'traefik.http.routers.rieger.entrypoints=websecure'
      - 'traefik.http.routers.rieger.tls.certresolver=letsencrypt'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.services.rieger.loadbalancer.server.port=3000'
    networks:
      - network

networks:
  traefik_web:
    external: true
