services:
  web:
    build: .
    container_name: rieger-web
    restart: always
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rieger.rule=Host(`rieger-systems.eu`)'
      - 'traefik.http.routers.rieger.entrypoints=websecure'
      - 'traefik.http.routers.rieger.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.rieger-http.rule=Host(`rieger-systems.eu`)'
      - 'traefik.http.routers.rieger-http.entrypoints=web'
      - 'traefik.http.routers.rieger-http.middlewares=redirect-to-https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
